spring.application.name=AurigaClinic

spring.datasource.url=jdbc:postgresql://localhost:5432/auriga_clinic
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true